### ISSUE TITLE
Another launch issue (Happens if atom launches before docker even starts to start up?)

### ISSUE THREAD

**Issue by kwerle** [kwerle/ide-ruby#12]
Happens if atom launches before docker even *starts* to start up?

```
Uncaught (in promise) Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at RubyLanguageClient.startServerProcess (/Users/kwerle/.atom/packages/ide-ruby/src/main.js:46:29)
    at RubyLanguageClient.startServer (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/auto-languageclient.js:187:32)
    at ServerManager._serverManager._serverManager.ServerManager.p [as _startServer] (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/auto-languageclient.js:156:70)
    at ServerManager.startServer (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/server-manager.js:134:34)
    at ServerManager.getServer (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/server-manager.js:129:73)
    at ServerManager._handleTextEditor (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/server-manager.js:71:33)
    at ServerManager._handleGrammarChange (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/server-manager.js:86:12)
    at editor.observeGrammar.grammar (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/server-manager.js:62:60)
    at TextEditor.observeGrammar (<embedded>:3058:11)
    at ServerManager.observeTextEditors (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/server-manager.js:62:29)
    at Set.forEach (native)
    at TextEditorRegistry.observe (<embedded>:34716:26)
    at ServerManager.startListening (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/server-manager.js:49:43)
    at RubyLanguageClient.activate (/Users/kwerle/.atom/packages/ide-html/node_modules/atom-languageclient/build/lib/auto-languageclient.js:157:25)
    at Package.module.exports.Package.activateNow (<embedded>:72535:25)
    at <embedded>:72507:38
    at Package.module.exports.Package.measure (<embedded>:72379:21)
    at <embedded>:72500:32
    at Package.module.exports.Package.activate (<embedded>:72497:40)
    at PackageManager.activatePackage (<embedded>:25356:42)
    at config.transactAsync (<embedded>:25331:36)
    at Config.module.exports.Config.transactAsync (<embedded>:22003:24)
    at PackageManager.activatePackages (<embedded>:25329:23)
    at PackageManager.activate (<embedded>:25308:50)
    at <embedded>:1103:36


```

**Comment by kwerle** [comment]
0.4.0
