### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by dbourguignon** [kwerle/ide-ruby#14]
[Enter steps to reproduce:]

Mostly, docker has been stopped

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [ide-ruby](https://github.com/kwerle/ide-ruby) package 0.1.10

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/davidbourguignon/.atom/packages/ide-ruby/node_modules/vscode-jsonrpc/lib/main.js:613

Error: Connection is closed.
    at /packages/ide-ruby/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-ruby/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-ruby/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-ruby/node_modules/atom-languageclient/build/lib/languageclient.js:242:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-ruby/node_modules/atom-languageclient/build/lib/languageclient.js:131:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-ruby/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:181:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.displayLayer.onDidChange.changes (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:595:26)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDeferredChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:819:26)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1756:30)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2708:23)
    at TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2519:23)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1801:25)
```

### Commands

```
     -0:39.3.0 core:paste (input.hidden-input)
  2x -0:38.4.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:38.1.0 core:move-down (input.hidden-input)
  4x -0:37.8.0 core:select-down (input.hidden-input)
     -0:36.7.0 editor:toggle-line-comments (input.hidden-input)
     -0:36.5.0 core:save (input.hidden-input)
     -0:30.2.0 window:reload (input.hidden-input)
  2x -0:21.9.0 core:save (input.hidden-input)
     -0:18.9.0 editor:consolidate-selections (input.hidden-input)
     -0:18.9.0 core:cancel (input.hidden-input)
     -0:18.1.0 core:save (input.hidden-input)
     -0:17.7.0 editor:consolidate-selections (input.hidden-input)
     -0:17.7.0 core:cancel (input.hidden-input)
     -0:15.4.0 editor:consolidate-selections (input.hidden-input)
     -0:15.4.0 core:cancel (input.hidden-input)
  2x -0:13.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-ruby 1.6.1 
atom-beautify 0.32.2 
atom-ide-ui 0.9.4 
busy-signal 1.4.3 
dash 1.7.1 
file-icons 2.1.18 
fonts 3.0.3 
gist-it 0.9.2 
highlight-selected 0.13.1 
ide-ruby 0.1.10 
ide-yaml 0.4.2 
intentions 1.1.5 
language-haml 0.31.0 
language-rspec 0.7.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-rubocop 2.2.3 
linter-ruby 1.2.6 
linter-stylelint 4.2.0 
linter-ui-default 1.7.1 
multi-cursor 2.1.5 
open-files 0.8.2 
rails-rspec 0.3.2 
rails-transporter 1.7.1 
react 0.18.0 
rspec 0.4.0 
ruby-block 0.3.6 
ruby-block-converter 4.0.1 
ruby-syntax-replacer 0.5.1 
scratch 1.2.0 
symbol-gen 1.3.1 
symbols-tree-view 0.14.0 
todo-show 2.2.0 
touchbar 0.6.1 
wakatime 7.0.4 
yaml-path 0.1.1 
```

**Comment by kwerle** [comment]
So - you killed docker (or something else happened to it) and ...?

**Comment by dbourguignon** [comment]
@kwerle sorry I thought the bug report was more precise :) 

Well… I killed docker because it was in 'full throttle' mode, then I start to get error from the plugin (no big surprise)
Issue was that the error keep going basically on each action (keystroke, …)

**Comment by kwerle** [comment]
Gotcha - I've seen the death spiral, but never by accident.  I'll see what I can do.

**Comment by kwerle** [comment]
I haven't seen the death spiral in a long time.  Have you?

**Comment by kwerle** [comment]
Can't reproduce
