### ISSUE TITLE
Failed to activate the ide-ruby package

### ISSUE THREAD

**Issue by mharrisjava** [kwerle/ide-ruby#29]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-ruby](https://github.com/kwerle/ide-ruby) package 0.5.0

### Stack Trace

Failed to activate the ide-ruby package

```
At Package not initialized

Error: Package not initialized
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:61:15)
    at Provider.provide (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1122140)
    at ServiceHub.provide (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3321702)
    at Package.activateServices (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3329988)
    at Package.activateNow (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326964)
    at measure (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326288)
    at Package.measure (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3323898)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326148)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326091)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:382452)
    at ~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:942215
    at r (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:936821)
    at n (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1125047)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1125253)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -4:57.2.0 run:file (input.hidden-input)
     -4:46.7.0 encoding-selector:show (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
     -4:36.8.0 line-ending-selector:show (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
  5x -1:18.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
ide-ruby 0.5.0 
```

**Comment by kwerle** [comment]
@mharrisjava 
Before I really dive into this - I didn't think you could run docker on Win-10-Home?

**Comment by AlexWayfer** [comment]
You already created the same #28…
